POST http://localhost:3000/users?role=superadmin
content-type: application/json

{
    "email": "gyusrulkhoi@gmail.com",
    "password": "rahasia123"
}

###Register Employeer

POST http://localhost:3000/users?role=employeer
content-type: application/json

{
    "firstname": "abc",
    "companyName": "abc",
    "username": "abc",
    "email": "abc@g.cps",
    "password": "rahaasdasdasdas"
}

###Register Employee

POST http://localhost:3000/users?role=employee
content-type: application/json

{
    "firstname": "abc",
    "username": "abc",
    "email": "abcd@g.cps",
    "password": "rahaasdasdasdas"
}